x-api-template: &api
  image: rinha-rust-2025
  environment:
    - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
    - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
    - PORT=3000
  networks:
    - backend
    - payment-processor

services:

  api-1:
    build: .
    <<: *api

  api-2:
    <<: *api

  load-balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
